# Generated by Django 4.2.3 on 2023-08-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
